<Project>
  <PropertyGroup>
    <VersionPrefix>1.1.0</VersionPrefix>
    <Version>1.1.0-beta.1-en</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0-beta.1-en</InformationalVersion>
    <Product>SyncWallpaper</Product>
    <Company>SyncWallpaper contributors</Company>
  </PropertyGroup>
</Project>
