<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SyncWallpaper.Core\SyncWallpaper.Core.csproj" />
    <ProjectReference Include="..\SyncWallpaper.DisplayEngine\SyncWallpaper.DisplayEngine.csproj" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="8.0.0" />
  </ItemGroup>

</Project>
